FROM node:18-slim
EXPOSE 3000

WORKDIR /app
USER root

# 安装 iproute2、vim
RUN apt-get update \
    && apt-get install -y iproute2 \
    && apt-get clean

COPY mnt/ /mnt/

COPY app/ ./

CMD ["node", "index.js"]